# Se usa una imagen base completa (pesada)
FROM node:22
WORKDIR /app

# Se copian los archivos e instalan las dependencias
COPY package*.json ./
RUN pnpm ci

# Se copia el resto del código fuente
COPY . .

# Se expone el puerto y se define el arranque
EXPOSE 3000
CMD ["npm", "start"]